### ISSUE TITLE
Primer dialogo

### ISSUE THREAD

**Issue by Carl3190** [SistemasInformacionComisionIII2016/PLATONSOCRATES#4]
[https://drive.google.com/open?id=0B0-wnnMd3BghSDJxZ1RrNEVKQlU](url)

**Comment by juankalbronoz88** [comment]
Escena 2
Personajes:

1. Procesos de negocios
2. Organización
3. Sistema Socio técnico

- Organización: pero vas a estar involucrando a un amigo mio que no tiene nada que ver, que el enfoque socio-técnico para que lo llamo.

- Enfoque Socio-técnico: para la mono que cuando yo vengo es porque es algo serio para ustedes.

- Proceso de negocio: yo solo decía que había que rever los conceptos un poco mas, por ahí había que ajustar los procesos nada mas.

- Enfoque Socio-técnico: si yo vengo es porque el personal y la tecnología se llevan a las patadas. ¿Es hacia o no?

- Organización: creo que no es para tanto.

- Proceso de negocio: Bueno, convenimos que debemos saber mas del asunto, si es algo conceptual o si el sistema informático por el cual se hace el pedido de la materia prima es el que falla o la persona que no lo sabe utilizar.

- Organización: creo que debo hablar con mi gente para estar seguros y analizar y valorar mejor la situación.

- Enfoque Socio-técnico: si la falla es por mi causa yo les explicare como abordar el tema. Nos vemos.
